---
name: CI
on:
  - push
  - pull_request
jobs:
  test_go:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.2.0
        with:
          go-version: 1.23
      - run: make build
      - run: make test
