---
name: CI
on:
  - push
  - pull_request
jobs:
  test_go:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    container:
      image: quay.io/prometheus/golang-builder:1.23-base
    steps:
      - uses: actions/checkout@v4.2.2
      #- name: Set up Go
      #  uses: actions/setup-go@vv5.2.0
      #  with:
      #    go-version: 1.23

      - name: Build
        run: make build

      - name: Test
        run: make test
