---
name: CI
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.2.0
        with:
          go-version: 1.23
      - run: make build
      - run: make test GOOPTS=-v

  build:
    strategy:
      matrix:
        thread: [0, 1, 2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: mkdir -p .build
      - run: pwd
      - run: ls -al
      - run: make promu
      - run: ~/go/bin/promu crossbuild -v --parallelism 3 --parallelism-thread ${{ matrix.thread }} -p linux
      - run: ls -al .build
      - uses: actions/upload-artifact@v4.5.0
        with:
          path: ${{ github.workspace }}/.build
          if-no-files-found: error
          include-hidden-files: true
